name: scope_function
description: A Dart implementation similar to Kotlin scope functions, enable you for powerful chained programming style.
version: 1.0.2
repository: https://github.com/techwnn/scope_function

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
